name: Deploy Website Agent - Azure Function App

on:
  push:
    paths:
      - './azure_functions/agents/Website/**'  # Trigger only if this folder changes
    branches:
      - azure_functions

env:
  PYTHON_VERSION: '3.13'  # Specify the Python version

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv ./azure_functions/agents/Website/.venv
          source ./azure_functions/agents/Website/.venv/bin/activate

      - name: Install dependencies
        run: pip install -r ./azure_functions/agents/Website/requirements.txt

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: zip release.zip ./azure_functions/agents/Website/* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !./azure_functions/agents/Website/.venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9A2802F03E0B4C01B669D7D0CC47ECED }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_38899D9DF1874FABAF0068D5E274F143 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6EFA4795D0814202AB11EDAD77204C9D }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'test-function-mvpagents'
          slot-name: 'Production'
          package: '.'